version: '2'

services:
  app:
    image: 'notes-application:latest'
    build:
      context: .
    container_name: notes_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notes_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: notes_db
    environment:
      - POSTGRES_DB=notes_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres